[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=69", "wheel"]

[project]
dependencies = [
  "cryptography",
  "typer",
]
description = "Tools for encrypting and decrypting text files"
name = "fscrypt"
requires-python = ">=3.11"
version = "0.1.0"

[project.optional-dependencies]
test = [
  "pytest",
  "pyfakefs",
]

[project.scripts]
fscrypt = "fscrypt.main:main"

[tool.setuptools.packages.find]
where = ["src"]
