[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fsencrypt"
version = "0.1.0"
description = "Tools for encrypting and decrypting text files"
requires-python = ">=3.11"
dependencies = [
    "cryptography",
    "typer",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pyfakefs",
]

[project.scripts]
fsencrypt = "fsencrypt.main:main"

[tool.setuptools.packages.find]
where = ["src"]
